# Generated by Django 4.2.2 on 2023-06-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_constact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constact',
            new_name='Contact',
        ),
    ]
